version: '3'

services:
  service_a:
    image: sso-service
    env_file: .env-a.production
    networks:
      - sso
      - nginx
  service_b:
    image: sso-service
    env_file: .env-b.production
    networks:
      - sso
      - nginx
networks:
  sso:
    external: true
  nginx:
    external: true
