version: '3'

services:
  sso_service_a:
    image: sso-service
    env_file: .env-a.production
    networks:
      - sso
  sso_service_b:
    image: sso-service
    env_file: .env-b.production
    networks:
      - sso
networks:
  sso:
    external: true
