// @generated by protobuf-ts 2.8.2
// @generated from protobuf file "auth/auth.proto" (package "auth", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthService } from "./auth";
import type { TokenPayload } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { BoolValue } from "../google/protobuf/wrappers";
import type { Token } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service auth.AuthService
 */
export interface IAuthServiceClient {
    /**
     * @generated from protobuf rpc: VerifyToken(auth.Token) returns (google.protobuf.BoolValue);
     */
    verifyToken(input: Token, options?: RpcOptions): UnaryCall<Token, BoolValue>;
    /**
     * @generated from protobuf rpc: GenerateToken(auth.TokenPayload) returns (auth.Token);
     */
    generateToken(input: TokenPayload, options?: RpcOptions): UnaryCall<TokenPayload, Token>;
}
/**
 * @generated from protobuf service auth.AuthService
 */
export class AuthServiceClient implements IAuthServiceClient, ServiceInfo {
    typeName = AuthService.typeName;
    methods = AuthService.methods;
    options = AuthService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: VerifyToken(auth.Token) returns (google.protobuf.BoolValue);
     */
    verifyToken(input: Token, options?: RpcOptions): UnaryCall<Token, BoolValue> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Token, BoolValue>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GenerateToken(auth.TokenPayload) returns (auth.Token);
     */
    generateToken(input: TokenPayload, options?: RpcOptions): UnaryCall<TokenPayload, Token> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<TokenPayload, Token>("unary", this._transport, method, opt, input);
    }
}
