version: '3'

services:
  sso_server:
    image: sso-server
    # ports:
    #   - 3001:3001
    #   - 3002:3002
    env_file:
      - .env.production
    networks:
      - sso
networks:
  sso:
    external: true
