# Build Stage
FROM node:alpine as builder

ARG NPM_TOKEN

WORKDIR /app
COPY ./package.json /app
COPY ./yarn.lock /app
COPY ./.npmrc /app


RUN echo -e "\n//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" >> .npmrc
RUN cat .npmrc
RUN yarn install
RUN rm -f .npmrc

RUN yarn build


# Production Stage
FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]